### ISSUE TITLE
GDPR related changes

### ISSUE THREAD

**Issue by kreftl** [aertslab/SCope#148]
accordingly to the newest regulations cookies consent + GA consent must be gathered from the users prior to using this technologies

**Comment by KrisDavie** [comment]
I didn't think GA consent was required as the info gathered was only used for analytical purposes. But we should place a cookie consent at a minimum. 
UUID cookie I think falls into the 'required for operation' category so doesn't need consent. Others include sidebar setting (no tracking info) and the GA cookies.

**Comment by vibbits** [comment]
it is, and "only used for analytical purposes" is the explanation you need to give it to the user to obtain consent, especially since we are passing the UUID to the GA ( see https://www.blastam.com/blog/5-actionable-steps-gdpr-compliance-google-analytics)

also, as i only recently learned :P 
there is need to disclose use of GA to the user anyhow,  together with link to their webpage on how they process user's data (see pt 7 on https://www.google.com/analytics/terms/us.html)
this can go in about page i think

**Comment by KrisDavie** [comment]
Cookie warning has been added

**Comment by MaybeJustJames** [comment]
This can be closed per previous comment. Also, GA has been removed
