### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by sedjro** [aertslab/SCope#158]
the Scope page is loaded but WebSocket does not return anything.

**Comment by mase5** [comment]
Can you provide a more detailed description of the issue you encounter?

**Comment by KrisDavie** [comment]
This usually happens if you have multiple servers running, or your ports are not all correct. 

Can you confirm the ports that each of the servers are running on (in your config), and that they are the ports that the frontend it trying to connect to (This can be seen in the network tab of development tools, at least in chrome)?

Also the javascript console will print these lines as the top:
![image](https://user-images.githubusercontent.com/5079892/42270723-d9aa20b6-7f81-11e8-8ff3-eba50d458f1c.png)
Can you confirm what they say in your instance, and maybe post your webpack.config.js?

**Comment by mfiers** [comment]
You could have provided slightly more to go on Yannick

All runs well if we're on the machine that runs SCope
in the developer tools it seems to hang on a websocket call
the port in question is not used by anything else
the websocket calls seems to point to the correct address+port

**Comment by sedjro** [comment]
Console dump:

```
[HMR] Waiting for update signal from WDS...
SCope-1.0.3.e9d5d0d.js:203779 Download the React DevTools for a better development experience: https://fb.me/react-devtools
SCope-1.0.3.e9d5d0d.js:264281 Using config WSport
SCope-1.0.3.e9d5d0d.js:264289 Using config RPCport
SCope-1.0.3.e9d5d0d.js:264291 55852 55853
SCope-1.0.3.e9d5d0d.js:264299 Promise {_id: 6, _label: undefined, _state: undefined, _result: undefined, _subscribers: Array(0)}
SCope-1.0.3.e9d5d0d.js:263151 App componentWillMount {match: {…}, location: {…}, history: {…}, staticContext: undefined, cookies: Cookies, …}
SCope-1.0.3.e9d5d0d.js:263188 Query params - loom:  undefined  page:  undefined
SCope-1.0.3.e9d5d0d.js:263029 isSidebarVisible true
SCope-1.0.3.e9d5d0d.js:54630 WebSocket connection to 'ws://127.0.0.1:55852/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/grpc-bus-websocket-client/index.js.GBC.connect @ SCope-1.0.3.e9d5d0d.js:54630
API @ SCope-1.0.3.e9d5d0d.js:264297
(anonymous) @ SCope-1.0.3.e9d5d0d.js:265039
./src/components/common/API.jsx @ SCope-1.0.3.e9d5d0d.js:265042
__webpack_require__ @ SCope-1.0.3.e9d5d0d.js:679
fn @ SCope-1.0.3.e9d5d0d.js:89
(anonymous) @ SCope-1.0.3.e9d5d0d.js:263406
./src/components/AppHeader.jsx @ SCope-1.0.3.e9d5d0d.js:263691
__webpack_require__ @ SCope-1.0.3.e9d5d0d.js:679
fn @ SCope-1.0.3.e9d5d0d.js:89
(anonymous) @ SCope-1.0.3.e9d5d0d.js:262870
./src/components/App.jsx @ SCope-1.0.3.e9d5d0d.js:263394
__webpack_require__ @ SCope-1.0.3.e9d5d0d.js:679
fn @ SCope-1.0.3.e9d5d0d.js:89
(anonymous) @ SCope-1.0.3.e9d5d0d.js:271432
./src/main.jsx @ SCope-1.0.3.e9d5d0d.js:271483
__webpack_require__ @ SCope-1.0.3.e9d5d0d.js:679
fn @ SCope-1.0.3.e9d5d0d.js:89
1 @ SCope-1.0.3.e9d5d0d.js:271500
__webpack_require__ @ SCope-1.0.3.e9d5d0d.js:679
./node_modules/add-dom-event-listener/lib/EventBaseObject.js.Object.defineProperty.value @ SCope-1.0.3.e9d5d0d.js:725
(anonymous) @ SCope-1.0.3.e9d5d0d.js:728
SCope-1.0.3.e9d5d0d.js:263224 Cookie UUID detected
SCope-1.0.3.e9d5d0d.js:263029 isSidebarVisible true
SCope-1.0.3.e9d5d0d.js:262181 [WDS] Hot Module Replacement enabled.
SCope-1.0.3.e9d5d0d.js:262251 [WDS] Warnings while compiling.
warnings @ SCope-1.0.3.e9d5d0d.js:262251
onmessage @ SCope-1.0.3.e9d5d0d.js:262539
EventTarget.dispatchEvent @ SCope-1.0.3.e9d5d0d.js:248210
(anonymous) @ SCope-1.0.3.e9d5d0d.js:248923
SockJS._transportMessage @ SCope-1.0.3.e9d5d0d.js:248921
EventEmitter.emit @ SCope-1.0.3.e9d5d0d.js:248126
WebSocketTransport.ws.onmessage @ SCope-1.0.3.e9d5d0d.js:250997
SCope-1.0.3.e9d5d0d.js:262257 ./node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/encoding/lib/iconv-loader.js
 @ ./node_modules/encoding/lib/encoding.js
 @ ./node_modules/node-fetch/lib/body.js
 @ ./node_modules/node-fetch/index.js
 @ ./node_modules/bitlyapi/src/bitly.js
 @ ./src/components/AppHeader.jsx
 @ ./src/components/App.jsx
 @ ./src/main.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:55850 webpack/hot/dev-server react-hot-loader/patch ./src/main.jsx
```

the websocket error is clear - I guess. but in the network tab we have two websocket calls hanging. One to localhost, the other to the proper server address. 

config is: 

{
    "debug": true,
    "domainName": "10.34.182.159",
    "httpProtocol": "http",
    "wsProtocol": "ws",
    "mPort": "55850",
    "pPort": "55851",
    "xPort": "55852",
    "gPort": "55853",
    "reverseProxyOn": false
}

**Comment by KrisDavie** [comment]
So you are getting this error:
`SCope-1.0.3.e9d5d0d.js:54630 WebSocket connection to 'ws://127.0.0.1:55852/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
`
Which means that [this](https://github.com/aertslab/SCope/blob/master/webpack.config.js#L69) setting in your webpack.config.js is still set to 127.0.0.1 and not 10.34.182.159, so the frontend is trying to connect to a version of the scope backend on your computer, rather than the one on your server. Try changing that and restarting everything. Let me know fi that works so that I can close the issue.

**Comment by sedjro** [comment]
I changed the address in webpack.config.js.
It's working now.
